version: '3.9'

services:
  cassandra:
    image: cassandra:5.0
    container_name: cassandra
    restart: unless-stopped
    ports:
      - "9042:9042"
    environment:
      CASSANDRA_CLUSTER_NAME: "LocalCluster"
      CASSANDRA_DC: "datacenter1"
      CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
      CASSANDRA_START_RPC: "true"
      MAX_HEAP_SIZE: 512M
      HEAP_NEWSIZE: 256M
    volumes:
      - cassandra-data:/var/lib/cassandra
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'describe keyspaces'"]
      interval: 15s
      timeout: 10s
      retries: 5

volumes:
  cassandra-data:
